from pathlib import Path
base=Path(__file__).resolve().parent
source=(base/'s13_service_accept_v2.py').read_text(encoding='utf-8')
source=source.replace("tests_run']==1828","tests_run']==1850").replace("len(pipeline['commands'])==7","len(pipeline['commands'])==8")
source=source.replace('from s13_acceptance_integrity import','from s13_ssh_acceptance_integrity import')
source=source.replace("native_scenarios']==36 and integrity['native_commands']==40","native_scenarios']==46 and integrity['native_commands']==50")
source=source.replace("service-{short}-py312","ssh-{short}-py312").replace("service-artifact-hashes-{short}.json","ssh-artifact-hashes-{short}.json")
source=source.replace("'native-recovery.json','native-service-denial.json')","'native-recovery.json','native-service-denial.json','native-ssh-access.json')")
source=source.replace("top(denial_root,'native-service-denial')","top(denial_root,'native-service-denial')\nssh_root=project/f'artifacts/r7-native-S13-ssh-access-{short}'\nssh=load(ssh_root/'native-ssh-access.json');top(ssh_root,'native-ssh-access')")
source=source.replace("for pattern in ('S13-service-*.log'","for pattern in ('S13-ssh-*.log','S13-service-*.log'")
source=source.replace("for name in ('s13_service_ui_frontend.py'","retain(project/'artifacts/S13-ssh-independent-source-review.json','review/ssh-source-review.json')\nretain(project/'artifacts/S13-ssh-independent-harness-review.json','review/ssh-harness-review.json')\nfor name in ('s13_ssh_qualify.py','s13_ssh_candidate_pipeline.py','s13_native_ssh_probe.py','s13_native_access_integrity.py','s13_native_access_integrity_tests.py',\n    's13_native_ssh_probe_reviewed_v1.py','run_s13_native_integrity_tests.py','s13_ssh_acceptance_integrity.py','s13_ssh_acceptance_integrity_tests.py',\n    'run_s13_ssh_integrity_tests.py','s13_prepare_ssh_accept.py','s13_ssh_accept.py','s13_prepare_ssh_qualification.py','s13_record_ssh_checkpoint.py','s13_record_ssh_reviews.py',\n    's13_service_ui_frontend.py'")
source=source.replace("build_root:'native-build',denial_root:'native-service-denial'","build_root:'native-build',denial_root:'native-service-denial',ssh_root:'native-ssh-access'")
source=source.replace("previous_qualified_executable_revision='86643c4b0444db2cfb33ce071618c1e3f708ad37'","previous_qualified_executable_revision='14aeb991aef9d92705cdf0a1151a2df2893e02bb'")
source=source.replace("scope='GUARDED_SERVICE_SOURCE_AND_SCOPED_WINDOWS_RECOVERY;UBUNTU_SERVICE_NOT_RUN'","scope='SSH_PLAN_AND_NATIVE_PUBLIC_LOOPBACK_ACCESS_WITH_SCOPED_WINDOWS_RECOVERY;UBUNTU_AND_REAL_SSH_NOT_RUN'")
source=source.replace("+len(denial['scenarios']),","+len(denial['scenarios'])+len(ssh['scenarios']),")
source=source.replace("+len(denial['commands']),","+len(denial['commands'])+len(ssh['commands']),")
source=source.replace("windows_service_platform_denial=3,smoke=", "ssh_access_scenarios=10,ssh_access_commands=10,real_ssh='NOT_RUN',windows_service_platform_denial=3,smoke=")
source=source.replace("pending=['S13 native service install/uninstall/SSH code and actual Ubuntu package/systemd/reboot qualification'","pending=['S13 native service install/uninstall code and actual Ubuntu package/systemd/reboot/SSH qualification'")
source=source.replace("progress['service_increment'].update","progress['ssh_access_increment'].update")
source=source.replace("progress['service_qualified_checkpoint']","progress['ssh_qualified_checkpoint']")
source=source.replace("scope='SERVICE_SOURCE_AND_WINDOWS_RECOVERY_ONLY;UBUNTU_NOT_RUN'","scope='SSH_SOURCE_NATIVE_PUBLIC_ACCESS_AND_WINDOWS_RECOVERY;UBUNTU_REAL_SSH_NOT_RUN'")
source=source.replace('S13 scoped service/recovery executable','S13 scoped SSH/public-access/recovery executable')
source=source.replace('across service platform denial/smoke/research/offline bridge/private recovery PASS','across SSH plan/public access/service platform denial/smoke/research/offline bridge/private recovery PASS')
source=source.replace("assert ui['initial_attempt']['status']", "ssh_source_review=load(project/'artifacts/S13-ssh-independent-source-review.json')\nassert ssh_source_review['remaining_critical']==ssh_source_review['remaining_important']==0\nfor name,expected in ssh_source_review['reviewed_source_hashes'].items():assert hash_bytes((root/name).read_bytes())==expected\nssh_harness_review=load(project/'artifacts/S13-ssh-independent-harness-review.json')\nassert ssh_harness_review['remaining_critical']==ssh_harness_review['remaining_important']==0\nfor name,expected in ssh_harness_review['harness_hashes'].items():assert hash_bytes((project/'artifacts'/name).read_bytes())==expected\nassert ui['initial_attempt']['status']")
target=base/'s13_ssh_accept.py';assert not target.exists();compile(source,target.name,'exec')
target.write_text(source,encoding='utf-8',newline='\n')
runner=(base/'run_s13_integrity_tests.py').read_text(encoding='utf-8').replace('s13_acceptance_integrity_tests.py','s13_ssh_acceptance_integrity_tests.py')
target=base/'run_s13_ssh_integrity_tests.py';assert not target.exists();target.write_text(runner,encoding='utf-8',newline='\n')
print('Fresh SSH evidence collector and guarded test launcher prepared')
